---

- name: wbc server
  hosts: wbc
  remote_user: root
  tasks:
  - include: tasks/packages.yml
    tags: ['packages']
  - include: tasks/postgis.yml
    tags: ['postgis']
  - include: tasks/tilestache.yml
    tags: ['tilestache']
