---

- name: install mapnik packages
  apt: name={{item}} state=present
  with_items:
  - libmapnik2-dev
  - python-mapnik
  - python-pip
  - python-virtualenv
  - python-pil

- name: create directories
  file: path=/srv/gis/{{item}} state=directory mode=0755 owner=gis group=gis
  with_items:
  - layers
  - mapnik
  - tilestache
  - cache

- name: create virtualenv and install packages
  pip: name={{item}} virtualenv=/srv/gis/env virtualenv_site_packages=yes
  with_items:
  - nik2img
  - modestmaps
  - simplejson
  - werkzeug
  - TileStache

- name: copy tilestache config and wsgi
  copy: src={{item}} dest=/srv/gis/tilestache/{{item}}
  with_items:
  - tilestache.cfg
  - wsgi.py

- name: fetch bbs-mapnik from github
  git: repo=https://github.com/webuildcity/bbs-mapnik.git dest=/srv/gis/mapnik/bbs

- name: set permissions on folders
  file: path=/srv/gis/{{item}} owner=gis group=gis recurse=yes
  with_items:
  - env
  - mapnik
